# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# executors:
#   my-executor:
#     docker:
#         - image: cimg/base:stable
# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  create_infrastructure: 
      docker:
        - image: amazon/aws-cli
      steps:
        - checkout
        - run:
            name: Create Cloudformation Stack
            command: |
              aws cloudformation deploy \
                --template-file template.yml \
                --stack-name myStack-${CIRCLE_WORKFLOW_ID:0:5} \
                --region us-east-1

  configure_infrastructure: 
      docker:
        - image: python:3.9.16
      steps:
        - checkout
        - add_ssh_keys:
                # You can get this ID in the section where you registered the SSH Key
                fingerprints: ["c1:d9:3f:ae:2e:37:e3:7e:d9:ee:77:e7:84:b9:e6:e1"] 
        - run:
            name: Install Ansible
            command: |
              pip install ansible
        - run:
            name: Run Playbook and Configure server
            command: |
              ansible-playbook -i inventory main-remote.yml

  # save_hello_world_output:
  #   # Specify the execution environment. You can specify an image from Dockerhub or use one of our Convenience Images from CircleCI's Developer Hub.
  #   # See: https://circleci.com/docs/2.0/configuration-reference/#docker-machine-macos-windows-executor
  #   executor: my-executor
  #   # Add steps to the job
  #   # See: https://circleci.com/docs/2.0/configuration-reference/#steps
  #   steps:
  #     - checkout
  #     - run: mkdir /tmp/workspace
  #     - run:
  #         name: "Save hello world to file"
  #         command: echo "Hello World" > /tmp/workspace/output.txt
  #     - persist_to_workspace:
  #         root: /tmp/workspace
  #         paths: 
  #             - output.txt
  
  # print_output_file:
  #   # Specify the execution environment. You can specify an image from Dockerhub or use one of our Convenience Images from CircleCI's Developer Hub.
  #   # See: https://circleci.com/docs/2.0/configuration-reference/#docker-machine-macos-windows-executor
  #   executor: my-executor
  #   # Add steps to the job
  #   # See: https://circleci.com/docs/2.0/configuration-reference/#steps
  #   steps:
  #     - attach_workspace:
  #         at: /tmp/workspace
  #     - run: |
  #         if [[ `cat /tmp/workspace/output.txt` == "Hello World" ]]; then
  #             echo "It worked!";
  #         else
  #             echo "Nope, not yet!"; exit 1
  #         fi

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  print-hello-workflow:
    jobs:
      # - create_infrastructure
      - configure_infrastructure
      # - save_hello_world_output
      # - print_output_file:
      #     requires:
      #       - save_hello_world_output